### ISSUE TITLE
Documentation needed for standalone launchers

### ISSUE THREAD

**Issue by weeheavy** [Wintermute0110/plugin.program.AEL.dev#118]
Durding my own unlucky google-fu I found several threads where people want to launch browsers using this plugin. But the documentation for standalone launchers is missing. Is there any chance to get some kind of starting tips or examples?

Thank you in advance.

**Comment by Wintermute0110** [comment]
Sorry for not having proper docs... AEL is still in heavy development and it takes a lot of time to write documentation that will get obsolete quickly.

I recommend you use XML files to configure AEL. Creating a standalone launcher is simple, for example:

```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<advanced_emulator_launcher_configuration>
<launcher>
  <name>Retroarch</name>
  <application>/home/kodi/bin/retroarch</application>
</launcher>
</advanced_emulator_launcher_configuration>
```

This will create a Launcher named Retroarch with no category. Have a look at the examples in the AEL asset library for more tags you can use (arguments, artwork for the launcher, etc.). You can also use the New Launcher wizard in AEL, open the context menu in on any item and select "Add New Launcher", then select Stand Alone Launcher.

If you use Windows you can also use LNK files. You have some documentation in the first post of AEL thread in the Kodi forum.
